services:
  pokemon-chat-app:
    build: .
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///pokemon_chat.db
      # AI Configuration - Add your API keys here or use .env file
      - AI_PROVIDER=${AI_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env  # Optional: Load from .env file if it exists
    volumes:
      - pokemon_data:/app/instance
      - pokemon_uploads:/app/instance/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pokemon_data:
    driver: local
  pokemon_uploads:
    driver: local